---
# config/altmedia.yml

default: &default
  expect_url: ssh://altmedia@vm161.lib.berkeley.edu/home/altmedia/bin/mkcallnote
  mail_admin_email: prntscan@lists.berkeley.edu
  mail_confirm_email: baker@library.berkeley.edu
  mail_smtp_password: <%= ENV['MAIL_PASSWORD'] %>
  mail_smtp_username: lib-noreply@berkeley.edu
  patron_url: https://dev-oskicatp.berkeley.edu:54620/PATRONAPI/

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
  patron_url: https://oskicatp.berkeley.edu:54620/PATRONAPI/
