---
# config/altmedia.yml

default: &default
  expect_url: <%= ENV["PATRON_UPDATE_URL"] || "ssh://altmedia@vm161.lib.berkeley.edu/home/altmedia/bin/mkcallnote" %>
  mail_admin_email: <%= ENV["ADMIN_EMAIL"] || "prntscan@lists.berkeley.edu" %>
  mail_confirm_email: <%= ENV["CONFIRM_EMAIL"] || "baker@library.berkeley.edu" %>
  mail_privdesk_email: <%= ENV["PRIVDESK_EMAIL"] || "privdesk@library.berkeley.edu" %>
  mail_smtp_password: <%= ENV["MAIL_PASSWORD"] %>
  mail_smtp_username: <%= ENV["MAIL_USERNAME"] || "lib-noreply@berkeley.edu" %>
  # $PATRON_API_URL is set in https://git.lib.berkeley.edu/ops/docker-swarm/blob/master/files/production/swarm/stacks/framework.yml
  patron_url: <%= ENV["PATRON_API_URL"] || "https://dev-oskicatp.berkeley.edu:54620/PATRONAPI/" %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
