---

development:
  url: <%= ENV['DATABASE_URL'] || 'postgres://root:root@db/framework-dev?pool=5' %>
  
test:
  url: <%= ENV['DATABASE_URL'] ||'postgres://root:root@db/framework-test?pool=3' %>

production:
  url: <%= ENV['DATABASE_URL'] || 'postgres://root:root@db/framework-prod' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5).to_i + ENV.fetch("GOOD_JOB_MAX_THREADS", 4).to_i %>
