---

development:
  url: <%= ENV['DATABASE_URL'] || 'postgres://root:root@db/lostandfound-test?pool=5' %>

test:
  url: <%= ENV['DATABASE_URL'] ||'postgres://root:root@db/lostandfound-test?pool=5' %>

production:
  url: <%= ENV['DATABASE_URL'] || 'postgres://root:root@db/lostandfound-test' %>
