default: &default

  valid_groups:
    - UNDERGRADSLE
    - GRADSTUD
    - UCBVISSCHOL
    - FACULTY
    - NONACAD
    - UCOP
    - UNDERGRAD
    - EXECUTIVE
    - UCEXT
    - UCEXTSTUD
    - UCB POST
    - LIBSTAFF
    - UCBAFFILI
    - LIBSTAFFRS 
    - NONACADRS 
    - HHI
    - UCBALUMSTF

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
