---
# config/secrets.yml

development:
  secret_key_base: 0cebf923fcdcb065173f745999652c32f5dfb30eb89061c3ec94ae80aa123c13e57355d3b00d1e0ee6b47217acb1801a846c9c668a38a6a61fdb7802a47b59e8

test:
  secret_key_base: a4313b9cd26b025b60ef477649d8666de6f1b5d34e8176005dcb70a769ec6d632105bb1e7e2bbcb6261b9aef60da9c94d67d27ecb7efe704ecdc59c50bee48b3

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
