---
# config/secrets.yml

development:
  secret_key_base: 0cebf923fcdcb065173f745999652c32f5dfb30eb89061c3ec94ae80aa123c13e57355d3b00d1e0ee6b47217acb1801a846c9c668a38a6a61fdb7802a47b59e8

test:
  secret_key_base: a4313b9cd26b025b60ef477649d8666de6f1b5d34e8176005dcb70a769ec6d632105bb1e7e2bbcb6261b9aef60da9c94d67d27ecb7efe704ecdc59c50bee48b3

staging:
  secret_key_base: 75fb58ba101fdce458b0e76277b3e91a187d8de831ad5f25ae69922d884584e47f4ce86c8c6428a41e318e0083600c14cf539f4336c73eae1398a80605d3513b

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
